DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS step;
DROP TABLE IF EXISTS task;

CREATE TABLE post(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(100),
	description VARCHAR(100)
);

CREATE TABLE task(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	privated BOOLEAN,
	description VARCHAR(100),
	due_data DATE,
	steps_id INT,
	finished BOOLEAN
);

CREATE TABLE step (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	description VARCHAR(100),
	finished BOOLEAN
);

CREATE TABLE users (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	login VARCHAR(100),
	password_hash VARCHAR(100),
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	rating DOUBLE,
	birthday DATE,
	user_role VARCHAR(100),
	photo VARCHAR(100)
);

